### ISSUE TITLE
widgets for boards do not refresh automatically

### ISSUE THREAD

**Issue by jaal** [oryanm/TrelloWidget#34] opened 2018-08-01 09:52 UTC
I created two widgets for two boards and they do not refresh automatically. Button "refresh" doesn't work too.

**Comment by ailjushkin** [comment] 2018-08-24 07:14
@oryanm I agree with you. It's a bug.

**Comment by oryanm** [comment] 2019-03-24 17:42
duplicate of [issue 7](https://github.com/oryanm/TrelloWidget/issues/7)

**Closed as completed by oryanm** 2019-03-24 17:42 UTC
Labels: duplicate
